//!#version 440
#define COMPUTE 1
layout(local_size_x=16, local_size_y=16, local_size_z = 1) in;
#include "../raytracer.glsl"
layout(rgba32f, binding=0) uniform image2D directOutput;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	vec3 color;
	if(floatBitsToInt(HQSettings_sampleNum) == 0)
	{
		color = vec3(0);
	}
	else
	{
		color = imageLoad(directOutput, coord).xyz;
	}
    color += raytrace(gl_GlobalInvocationID.xy);
	
	imageStore(directOutput, coord, vec4(color, 1.0));
}